import re

text = """Arth AI is a cutting edge artificial intelligence driven wealth management and personal financial advisory platform designed to revolutionize how modern investors interact with their portfolios. Built with a sophisticated highly dynamic and premium glassmorphic user interface the application delivers an immersive visually stunning experience that prioritizes both aesthetics and functional depth. At its core Arth AI serves as a comprehensive digital wealth advisor guiding users through a seamless personalized financial journey from the moment they launch the application.

The platform features a robust onboarding flow that meticulously captures user preferences including language selection and detailed risk profiling ensuring that all financial recommendations are deeply tailored to individual investment appetites. Users can effortlessly manage their financial goals track real time portfolio performance and monitor their recent transaction activities through a centralized intuitive dashboard. A standout feature of the platform is the Portfolio Plan module which empowers users to generate download and review detailed personalized advisory reports in a convenient PDF format bridging the gap between automated insights and actionable financial strategies.

Technologically the project leverages a modern highly scalable stack. The frontend is powered by React and Vite utilizing advanced CSS animations custom keyframes and intricate glassmorphism techniques to create a fluid responsive and engaging user experience characterized by floating 3D elements and glowing animated backgrounds. The backend infrastructure relies on a robust Node environment integrated with Prisma ORM and a secure Supabase database ensuring rapid data retrieval seamless authentication and uncompromising data integrity.

Beyond standard portfolio tracking Arth AI distinguishes itself by offering an interactive AI advisory interface allowing users to seek intelligent data driven financial counsel at any time. Whether an investor is looking to explore impactful initiatives rebalance their assets based on shifting market dynamics or simply gain a clearer understanding of their long term financial trajectory Arth AI provides the necessary tools and insights. By seamlessly merging modern web technologies immersive design paradigms and intelligent financial algorithms Arth AI redefines the digital wealth management experience empowering users to make informed confident and strategic financial decisions with unparalleled clarity absolute precision complete confidence and truly maximum ease."""

words = text.split()
print(f"Count: {len(words)}")
