import { Router, Request, Response } from 'express';
import { requireAuth } from '../auth/auth.routes';
import { prisma } from '../../server';
import { TransactionsService } from '../transactions/transactions.service';
import { goalsService } from '../goals/goals.service';
import { createAuditLog } from '../audit/audit.service';

const router = Router();
const transactionsService = new TransactionsService();

router.get('/summary', requireAuth, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    
    const user = await prisma.userProfile.findUnique({ where: { userId } });
    const snapshot = await transactionsService.getFinancialSnapshot(userId);
    const goals = await prisma.goal.findMany({ where: { userId } });
    const risk = await prisma.riskAssessment.findFirst({ where: { userId }, orderBy: { createdAt: 'desc' } });
    const riskProfile = risk?.profile || 'Moderate';
    const enrichedGoals = goals.map(g => goalsService.calculateGoalFeasibility(g, riskProfile));
    
    // Fetch latest portfolio recommendation
    const portfolio = await prisma.portfolioRecommendation.findFirst({
      where: { userId },
      orderBy: { createdAt: 'desc' },
      include: { items: { include: { product: true } } }
    });

    // Generate Markdown Report
    const md = `
# Arth AI Advisory Summary
**Generated For:** ${user?.name || 'Customer'}
**Date:** ${new Date().toLocaleDateString()}
**Risk Profile:** ${riskProfile}

---

## 1. Financial Snapshot
- **Investable Surplus:** ₹${snapshot.investableSurplus.toLocaleString('en-IN')} / month
- **Financial Health Score:** ${snapshot.financialHealthScore}/100
- **Emergency Coverage:** ${snapshot.emergencyCoverageMonths.toFixed(1)} months
- **Estimated Liquid Assets:** ₹${(snapshot.emergencyCoverageMonths * snapshot.avgMonthlyExpense).toLocaleString('en-IN')} (Planning Proxy)

## 2. Explainable Health Breakdown
- **Savings Rate:** ${snapshot.healthBreakdown.savingsRate.value} (${snapshot.healthBreakdown.savingsRate.status})
- **Emergency Fund:** ${snapshot.healthBreakdown.emergencyFund.value} (${snapshot.healthBreakdown.emergencyFund.status})
- **Expense Stability:** ${snapshot.healthBreakdown.expenseStability.value} (${snapshot.healthBreakdown.expenseStability.status})
- **Goal Readiness:** ${snapshot.healthBreakdown.goalReadiness.value} (${snapshot.healthBreakdown.goalReadiness.status})

## 3. Goals and Gap Analysis
${enrichedGoals.length === 0 ? 'No active goals mapped.' : enrichedGoals.map(g => (
  `- **${g.name}**: Target ₹${g.target.toLocaleString('en-IN')} (Gap: ₹${g.gap.toLocaleString('en-IN')}). Required SIP: ₹${g.requiredMonthlyContribution.toLocaleString('en-IN')} (Assumed CAGR: ${g.assumedCagr * 100}%)`
)).join('\n')}

## 4. Latest Recommendation Basket
${!portfolio || portfolio.items.length === 0 ? 'No portfolio plan generated yet.' : portfolio.items.map(item => (
  `- **${item.product.name} (${item.percentage}%)**: ₹${item.amount.toLocaleString('en-IN')} / month
  *Rationale: ${item.rationale}*`
)).join('\n')}
${portfolio?.status === 'Consented' ? '\n*(Plan has been digitally consented by the user)*' : ''}

---

## 5. Assumptions and Limitations
- **Liquid Assets:** Liquid assets and net position are deterministic planning proxies derived from a base assumption plus transaction net flow.
- **Goal Gap CAGR:** Goal gaps use a risk-adjusted planning assumption (Conservative 8%, Moderate 12%, Aggressive 14%). Actual returns will vary.
- **Advisory Only:** Arth AI provides advisory logic but cannot execute trades.

---
*Generated by Arth AI Wealth Advisor. Compliant with SEBI Investment Adviser Regulations.*
`;

    // Audit logging for report generation
    await createAuditLog(
      userId,
      'Summary Report Downloaded',
      'System',
      {}
    );

    res.setHeader('Content-Type', 'text/markdown');
    res.setHeader('Content-Disposition', 'attachment; filename="ArthAI_Summary.md"');
    res.send(md.trim());

  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Failed to generate report' });
  }
});

export default router;
